# Generated by Django 3.0.7 on 2024-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20240805_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
