# Generated by Django 3.0.7 on 2024-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20240805_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='hello', max_length=1000),
            preserve_default=False,
        ),
    ]
